spring:
    application:
        name: dream-shops
    datasource:
        username: root
        password: 123456789
        url: jdbc:mysql://localhost:3306/dreamshops
    jpa:
        hibernate:
            ddl-auto: update
# none: Không thay đổi cơ sở dữ liệu.
# update: Cập nhật cơ sở dữ liệu để phù hợp với entity.
# create: Tạo lại cơ sở dữ liệu mỗi lần khởi động.
# create-drop: Tạo lại cơ sở dữ liệu và xóa khi dừng ứng dụng.
# validate: Kiểm tra sự khớp mà không thay đổi gì.
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: "quythan306@gmail.com"
        password: "okfhcqjzvretgtwg"
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 5MB

# giảm mức log của hibernate
# logging.level.org.hibernate=error

secret_key: BF7FD11ACE545745B7BA1AF98B6F156D127BC7BB544BAB6A4FD74E4FC7

api:
    prefix: /api/v1